default: &default
  adapter: postgresql
  encoding: unicode
  username: derik
  password: 123456789
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airbnb_development

test:
  <<: *default
  database: airbnb_test

production:
  <<: *default
  database: airbnb_production
  username: airbnb_clone
  password: <%= ENV["AIRBNB_CLONE_DATABASE_PASSWORD"] %>
